# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(verbose_name=datetime.datetime(2016, 5, 18, 10, 7, 3, 388224))),
            ],
        ),
    ]
